### ISSUE TITLE
Create tagged release

### ISSUE THREAD

**Issue by tomvanderlee** [agronick/BIR#2]
Hi! 

I put it on the Arch User Repository for you: [bir-git](https://aur.archlinux.org/packages/bir-git/). 
Maybe you could create a [tagged release](https://github.com/agronick/BIR/releases), so I can also put up a  "Stable" version instead of only a *-git version.

**Comment by agronick** [comment]
Thanks for pointing that out. I created one.

**Comment by tomvanderlee** [comment]
Stable is also on the AUR now: [bir](https://aur.archlinux.org/packages/bir/)!

**Comment by agronick** [comment]
Great thanks!
