### ISSUE TITLE
ibqt4-devel

### ISSUE THREAD

**Issue by dkebler** [agronick/BIR#3]
I am on ubuntu.  
I assume this is the same package?
libqt4-dev

**Comment by dkebler** [comment]
That is indeed it.  It complied.

**Comment by agronick** [comment]
I just loaded it on Elementary OS and found that was a huge difference between KDE and Gnome. I rewrote that part of the code. It does work fine on KDE but you're right it returns empty strings on Gnome based systems. All of the latest changes were done on Elementary OS and I tested everything so it should work fine now.
